#!/usr/bin/env sh

# Color Palette
BLACK=0xff181926
WHITE=0xffcad3f5
RED=0xffed8796
GREEN=0xffa6da95
BLUE=0xff8aadf4
YELLOW=0xffeed49f
ORANGE=0xfff5a97f
MAGENTA=0xffc6a0f6
GREY=0xff939ab7
TRANSPARENT=0x00000000

# General bar colors
BAR_COLOR=0xcc24273a
ICON_COLOR=$WHITE # Color of all icons
LABEL_COLOR=$WHITE # Color of all labels
BACKGROUND_1=0xff3c3e4f
BACKGROUND_2=0xff494d64

POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$WHITE

SHADOW_COLOR=$BLACK

# Labels
FONT="JetBrainsMono Nerd Font"
BG_PADDING=10
LABEL_FONT="$FONT:Bold:12"
LABEL_PADDING=5
ICON_FONT="$FONT:Regular:12"

# Backgrounds
BACKGROUND_PADDING=10
BACKGROUND_COLOR=0xff24283b

# General Icons
LOADING=ﱰ
APPLE=
PREFERENCES=漣
ACTIVITY=
LOCK=
BELL=
BELL_DOT=

# Git Icons
GIT_ISSUE=
GIT_DISCUSSION=
GIT_PULL_REQUEST=療
GIT_COMMIT=ﰖ
GIT_INDICATOR=

# Spotify Icons
SPOTIFY_BACK=倫
SPOTIFY_PLAY_PAUSE=懶
SPOTIFY_NEXT=淪
SPOTIFY_SHUFFLE=咽
SPOTIFY_REPEAT=凌

# Yabai Icons
YABAI_STACK=􀏭
YABAI_FULLSCREEN_ZOOM=􀏜
YABAI_PARENT_ZOOM=􀥃
YABAI_FLOAT=􀢌
YABAI_GRID=􀧍
